// enums
const PLAYER_MOVEMENTS = {
    x: 160,
    y: 300,
  };
  
  const SHAPE_DELAY = 3000;
  
  const TRIANGULO = "Triangulo";
  const CUADRADO = "Cuadrado";
  const ROMBO = "Rombo";
  const ROMBOMALO = "RomboMalo"

  const POINTS_PERCENTAGE = "value";
  const POINTS_PERCENTAGE_VALUE_START = 1;
  
  const SHAPES = [TRIANGULO, CUADRADO, ROMBO, ROMBOMALO];
  
  export { PLAYER_MOVEMENTS, SHAPE_DELAY, SHAPES, TRIANGULO, CUADRADO, ROMBO, ROMBOMALO, POINTS_PERCENTAGE_VALUE_START, POINTS_PERCENTAGE };